use phf::phf_map;
use evdev::Key;
use crate::ParseError;

// Perfect Hash Function static map (loads at compile time)
static KEY_MAP: phf::Map<&'static str, Key> = phf_map! {
    "q" => Key::KEY_Q,
    "w" => Key::KEY_W,
    "e" => Key::KEY_E,
    "r" => Key::KEY_R,
    "t" => Key::KEY_T,
    "y" => Key::KEY_Y,
    "u" => Key::KEY_U,
    "i" => Key::KEY_I,
    "o" => Key::KEY_O,
    "p" => Key::KEY_P,
    "a" => Key::KEY_A,
    "s" => Key::KEY_S,
    "d" => Key::KEY_D,
    "f" => Key::KEY_F,
    "g" => Key::KEY_G,
    "h" => Key::KEY_H,
    "j" => Key::KEY_J,
    "k" => Key::KEY_K,
    "l" => Key::KEY_L,
    "z" => Key::KEY_Z,
    "x" => Key::KEY_X,
    "c" => Key::KEY_C,
    "v" => Key::KEY_V,
    "b" => Key::KEY_B,
    "n" => Key::KEY_N,
    "m" => Key::KEY_M,
    "1" => Key::KEY_1,
    "2" => Key::KEY_2,
    "3" => Key::KEY_3,
    "4" => Key::KEY_4,
    "5" => Key::KEY_5,
    "6" => Key::KEY_6,
    "7" => Key::KEY_7,
    "8" => Key::KEY_8,
    "9" => Key::KEY_9,
    "0" => Key::KEY_0,
    "escape" => Key::KEY_ESC,
    "backspace" => Key::KEY_BACKSPACE,
    "capslock" => Key::KEY_CAPSLOCK,
    "return" => Key::KEY_ENTER,
    "enter" => Key::KEY_ENTER,
    "tab" => Key::KEY_TAB,
    "space" => Key::KEY_SPACE,
    "plus" => Key::KEY_KPPLUS,
    "minus" => Key::KEY_MINUS,
    "-" => Key::KEY_MINUS,
    "equal" => Key::KEY_EQUAL,
    "=" => Key::KEY_EQUAL,
    "grave" => Key::KEY_GRAVE,
    "`" => Key::KEY_GRAVE,
    "print" => Key::KEY_SYSRQ,
    "volumeup" => Key::KEY_VOLUMEUP,
    "volumedown" => Key::KEY_VOLUMEDOWN,
    "mute" => Key::KEY_MUTE,
    "brightnessup" => Key::KEY_BRIGHTNESSUP,
    "brightnessdown" => Key::KEY_BRIGHTNESSDOWN,
    "comma" => Key::KEY_COMMA,
    "," => Key::KEY_COMMA,
    "dot" => Key::KEY_DOT,
    "period" => Key::KEY_DOT,
    "." => Key::KEY_DOT,
    "slash" => Key::KEY_SLASH,
    "/" => Key::KEY_SLASH,
    "backslash" => Key::KEY_BACKSLASH,
    "\\" => Key::KEY_BACKSLASH,
    "leftbrace" => Key::KEY_LEFTBRACE,
    "[" => Key::KEY_LEFTBRACE,
    "rightbrace" => Key::KEY_RIGHTBRACE,
    "]" => Key::KEY_RIGHTBRACE,
    "semicolon" => Key::KEY_SEMICOLON,
    ";" => Key::KEY_SEMICOLON,
    "apostrophe" => Key::KEY_APOSTROPHE,
    "'" => Key::KEY_APOSTROPHE,
    "left" => Key::KEY_LEFT,
    "right" => Key::KEY_RIGHT,
    "up" => Key::KEY_UP,
    "down" => Key::KEY_DOWN,
    "pause" => Key::KEY_PAUSE,
    "home" => Key::KEY_HOME,
    "delete" => Key::KEY_DELETE,
    "insert" => Key::KEY_INSERT,
    "end" => Key::KEY_END,
    "pagedown" => Key::KEY_PAGEDOWN,
    "pageup" => Key::KEY_PAGEUP,
    "f1" => Key::KEY_F1,
    "f2" => Key::KEY_F2,
    "f3" => Key::KEY_F3,
    "f4" => Key::KEY_F4,
    "f5" => Key::KEY_F5,
    "f6" => Key::KEY_F6,
    "f7" => Key::KEY_F7,
    "f8" => Key::KEY_F8,
    "f9" => Key::KEY_F9,
    "f10" => Key::KEY_F10,
    "f11" => Key::KEY_F11,
    "f12" => Key::KEY_F12,
};

pub fn convert(s: &str) -> Result<Key, ParseError> {
    KEY_MAP
        .get(s)
        .copied()
        .ok_or_else(|| ParseError::InvalidKey(s.to_string()))
}
